version: '2'

services:
  backend:
    build:
      context: .
      args:
        - SERVICE_PORT=8001
      dockerfile: Dockerfile_backend
    ports:
      - "50001:8001"
  gui:
    build:
      context: .
      args:
        - REACT_APP_SERVICE_PORT=50001
        - REACT_APP_GUI_PORT=8002
      dockerfile: Dockerfile_frontend
    ports:
      - "8002:80"