from fastavro._validate_common import ValidationError
from fastavro.validation import validate_many

avro_schema ={
  "name":"PyScGenClass",
  "type":"record",
  "namespace":"com.pyscgen.avro",
  "fields":[
     {
        "name":"SntFOVersion",
        "type":"string"
     },
     {
        "name":"SntID",
        "type":"string"
     },
     {
        "name":"SntRVAbrechnung",
        "type":{
           "name":"SntRVAbrechnung",
           "type":"record",
           "fields":[
              {
                 "name":"SntFOVersion",
                 "type":"string"
              },
              {
                 "name":"SntID",
                 "type":"string"
              },
              {
                 "name":"SntRVAbrechnungRueckversicherungsbeleg",
                 "type":{
                    "name":"SntRVAbrechnungRueckversicherungsbeleg",
                    "type":"record",
                    "fields":[
                       {
                          "name":"Kundennummer",
                          "type":"string"
                       },
                       {
                          "name":"SntRVAbrechnungRueckversicherungsvertrag",
                          "type":{
                             "type":"array",
                             "items":[
                                "null",
                                {
                                   "name":"SntRVAbrechnungRueckversicherungsvertrag_record",
                                   "type":"record",
                                   "fields":[
                                      {
                                         "name":"SntRVAbrechnungExzedent",
                                         "type":[
                                            "null",
                                            {
                                               "type":"array",
                                               "items":[
                                                  "null",
                                                  {
                                                     "name":"SntRVAbrechnungExzedent_record",
                                                     "type":"record",
                                                     "fields":[
                                                        {
                                                           "name":"Risikoart",
                                                           "type":"string"
                                                        },
                                                        {
                                                           "name":"SntRVAbrechnungRisikoExzedent",
                                                           "type":[
                                                              "null",
                                                              {
                                                                 "type":"array",
                                                                 "items":[
                                                                    "null",
                                                                    {
                                                                       "name":"SntRVAbrechnungRisikoExzedent_record",
                                                                       "type":"record",
                                                                       "fields":[
                                                                          {
                                                                             "name":"AULeistungJN",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Abrechnungsverband",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"AntragsgenerationDatum",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Anwartschaftsende",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"BERSL",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Beitragsende",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Beitragsstatus",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Bergru",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"EndedatumStartoption",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"ExzedentID",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Familienstand",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"GDAT",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"GS",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Invalidisierungswahrscheinlichkeit",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Invaliditaetsbonus",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Jahresrente",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Kinderanzahl",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"KollektivpartnerNummer",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Kundennummer",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Leistungsart",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Leistungsbarwert",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"LeistungsdauerLebenslangJN",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Leistungsende",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"LeistungssteigerungssatzGarantiert",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Leistungszahlweise",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"ProduktID",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Quote",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"RSArt",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"RSIdentifikator",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"RVBeitragssatz",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"RVLeistung",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"RVPraemie",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Raucherstatus",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"RisikoIdentifikator",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Risikoart",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"RisikozuschlagSatzBeruf",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"RisikozuschlagSatzBesondereGefahren",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"RisikozuschlagSatzMedizinisch",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"RisikozuschlagSatzScoring",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"RueckversicherteRente",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"RueckversicherungsvertragID",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Scoringklasse",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Selbstbehalt",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"TarifID",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"VNR",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Versicherungsbeginn",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Versicherungsende",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"Vertragsstatus",
                                                                             "type":"string"
                                                                          },
                                                                          {
                                                                             "name":"XR",
                                                                             "type":"string"
                                                                          }
                                                                       ]
                                                                    }
                                                                 ]
                                                              }
                                                           ]
                                                        }
                                                     ]
                                                  }
                                               ]
                                            }
                                         ]
                                      }
                                   ]
                                }
                             ]
                          }
                       }
                    ]
                 }
              }
           ]
        }
     }
  ]
}
records = [
  {
     "SntFOVersion":"V_001_000_000",
     "SntID":"1",
     "SntRVAbrechnung":{
        "SntFOVersion":"V_001_000_000",
        "SntID":"1",
        "SntRVAbrechnungRueckversicherungsbeleg":{
           "Kundennummer":"2348793",
           "SntRVAbrechnungRueckversicherungsvertrag":[
              {
                 "SntRVAbrechnungExzedent":[
                    {
                       "Risikoart":"1",
                       "SntRVAbrechnungRisikoExzedent":[
                          {
                             "Abrechnungsverband":"None",
                             "AntragsgenerationDatum":"01.08.2023",
                             "Anwartschaftsende":"01.05.2066",
                             "AULeistungJN":"false",
                             "Beitragsende":"01.05.2066",
                             "Beitragsstatus":"Beitragspflichtig",
                             "Bergru":"BG1plus",
                             "BERSL":"0",
                             "EndedatumStartoption":"01.05.2021",
                             "ExzedentID":"1",
                             "Familienstand":"Undefiniert",
                             "GDAT":"2001-01-01",
                             "GS":"Maennlich",
                             "Invalidisierungswahrscheinlichkeit":"0.000082",
                             "Invaliditaetsbonus":"0.0",
                             "Jahresrente":"12000.0",
                             "Kinderanzahl":"0",
                             "KollektivpartnerNummer":"0",
                             "Kundennummer":"2348793",
                             "Leistungsart":"BURente",
                             "Leistungsbarwert":"118.826039",
                             "LeistungsdauerLebenslangJN":"false",
                             "Leistungsende":"01.05.2066",
                             "LeistungssteigerungssatzGarantiert":"Keine",
                             "Leistungszahlweise":"12",
                             "ProduktID":"SBU",
                             "Quote":"0.0",
                             "Raucherstatus":"Undefiniert",
                             "Risikoart":"1",
                             "RisikoIdentifikator":"1",
                             "RisikozuschlagSatzBeruf":"0.0",
                             "RisikozuschlagSatzBesondereGefahren":"0.0",
                             "RisikozuschlagSatzMedizinisch":"0.0",
                             "RisikozuschlagSatzScoring":"0.0",
                             "RSArt":"GrundLaufenderBeitrag",
                             "RSIdentifikator":"1",
                             "RueckversicherteRente":"0.0",
                             "RueckversicherungsvertragID":"1",
                             "RVBeitragssatz":"0.66",
                             "RVLeistung":"1.0",
                             "RVPraemie":"0.0",
                             "Scoringklasse":None,
                             "Selbstbehalt":None,
                             "TarifID":"SBU",
                             "Versicherungsbeginn":"01.05.2021",
                             "Versicherungsende":"01.05.2066",
                             "Vertragsstatus":"Aktiv",
                             "VNR":"80000010",
                             "XR":"21"
                          }
                       ]
                    }
                 ]
              }
           ]
        }
     }
  }
]

try:
    result = validate_many(records=records, schema=avro_schema, raise_errors=True)
except ValidationError as e:
    print(e)
    print(e.__str__().split(",")[-1].replace("\n", "")[:-1])


print(result)